### ISSUE TITLE
YAML Front Matter Formatting?

### ISSUE THREAD

**Issue by bobrocke** [textmate/markdown.tmbundle#28] opened 2015-02-08 16:44 UTC
Are there plans to add formatting for YAML front matter in a Markdown document? This is getting to be a pretty standard thing in many flat-file CMSs.

If there are no plans, how would I go about adding such a thing?

**Comment by sorbits** [comment] 2015-02-08 17:06
Duplicate of issue #27.

As for how to add this, do you know how grammars work? If not, you can 
read about them here: http://manual.macromates.com/en/language_grammars

In this specific case, I suggest using “injection”, which isn’t 
described by the 1.x manual, but I gave an example of extending Markdown 
syntax via injection here: 
https://github.com/textmate/markdown.tmbundle/issues/15#issuecomment-18321960 
— as mentioned in the duplicate issue, you should probably make your 
injected grammar start by matching `\A`, so that it only matches at the 
beginning of the document.

**Closed** 2015-02-08 17:06 UTC
Labels: duplicate

**Comment by bobrocke** [comment] 2015-02-08 17:12
The `\A` was the trick I was missing. Thanks!

For anyone following along behind, here's the injected grammar that worked for me:
```
{	patterns = (
		{	name = 'text.html.markdown.yaml';
			begin = '\A^[-]{3}';
			end = '[-]{3}\n';
			patterns = ( { include = 'source.yaml'; } );
		},
	);
}
```
