### ISSUE TITLE
Code not formatted properly

### ISSUE THREAD

**Issue by ataiya** [textmate/markdown.tmbundle#36] opened 2015-09-05 07:56 UTC
Snapshot is self explanatory:
<img width="752" alt="screenshot 2015-09-05 00 53 33" src="https://cloud.githubusercontent.com/assets/4480573/9698399/bfddf704-5368-11e5-8302-bd3e3444fe25.png">

Compare it with how this code looks:
```cpp
///========================== main.cpp ==========================
/// iostream provides basic input/output functionalities (cout)
#include <iostream>
/// iostream is part of the "std" namespace. The keyword "using" can 
/// be employed to avoid typing std::cout throughout the code
using namespace std;

/// main is the entry point of your program. It needs to be 
/// defined and always have this signature. The argc and argv 
/// are used to pass parameters from command line.
int main(int /*argc*/, char** /*argv*/){
    /// @todo find out how to print "helloworld" to terminal
    /// @solution  
    cout << "helloworld" << endl;
    
    /// The main function should always return a value.
    /// This tells the application whether it exited 
    /// correctly or not (legacy error management)
    return EXIT_SUCCESS;
}
```

Also, disabling **soft-text wrap** in textmate whenever you are in a code block would be a good idea!

**Comment by sorbits** [comment] 2015-09-05 08:17
By looking at your picture I think this is a duplicate of #15 (which 
shows you how you can extend TextMate to support non-standard Markdown 
like fenced code blocks).

**Closed by sorbits** 2015-09-05 08:17 UTC
Labels: duplicate

**Comment by ataiya** [comment] 2015-09-05 10:16
Still, it'd be nice to have this built-in the current Markdown bundle (and perhaps just disabled by default?)

**Comment by sorbits** [comment] 2015-09-05 10:38
Feel free to submit a pull request.

**Comment by ataiya** [comment] 2015-09-05 16:01
Hey Allan, sorry I don't know enough about regex and TM in general to submit a pull request.

**Comment by sorbits** [comment] 2015-09-06 08:52
Did you read the issue I referenced? I gave a “how to” in one of the 
comments.

**Comment by MikeMcQuaid** [comment] 2016-05-27 11:15
TextMate 2 now has a Markdown (GitHub) bundle under "Bundles" that I think may address many of the folks' desires here (repository for the curious: https://github.com/MikeMcQuaid/GitHub-Markdown.tmbundle).

**Comment by ataiya** [comment] 2016-05-29 08:04
Tiny question, is the change in font size for the # symbol a bug or a feature? ;)

![screenshot 2016-05-29 01 03 53](https://cloud.githubusercontent.com/assets/4480573/15632013/534ba25a-2539-11e6-94ca-533eb15adc7b.png)

**Comment by MikeMcQuaid** [comment] 2016-05-29 09:48
@ataiya A feature and should only be part of https://github.com/mikemcquaid/GitHub-Markdown-Font-Settings.tmbundle.
